version: '20'
services:
  dev-db:
  image: postgres:latest
  ports:
  - 5434:5432
  environment:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ahmad327
  POSTGRES_DB: nest

  networks:
  - freecodecamp
